[de]
contentDir = "content/deutsch"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = ""
title = "Clash Podcast"
weight = 2
[en]
contentDir = "content/english"
copyright = "© Clash Podcast 2022. This content is not affiliated with, endorsed, sponsored, or specifically approved by Supercell and Supercell is not responsible for it. For more information see [Supercell’s Fan Content Policy](https://www.supercell.com/fan-content-policy) <a rel=\"me\" href=\"https://mastodon.social/@clashfiles\">.</a>"
footer_content = "The Clash Files is the best Podcast, Scrim, and Clan Community in Supercell Games - Clash of Clans, Clash Royale, Everdale, and more. We share attack strategies, upgrade advice, game news, and base design."
footer_menu_left = "Gameplay"
footer_menu_middle = "Community"
footer_menu_right = "About Us"
languageName = "En"
title = "Clash Podcast"
weight = 1
