[[footer_left]]
name = "Clash Clans"
url = "clans"
[[footer_left]]
name = "Clash Esports"
url = "esports"
[[footer_left]]
name = "Clash Scrims"
url = "scrims"
[[footer_middle]]
name = "Brick Oven Bulletin"
url = "blog"
[[footer_middle]]
name = "Clash Podcasts"
url = "podcasts"
[[footer_middle]]
name = "Discord Server"
url = "https://discord.gg/clashfiles"
[[footer_right]]
name = "Frequently Asked"
url = "faq"
[[footer_right]]
name = "Rules & Guidelines"
url = "terms-conditions"
[[footer_right]]
name = "Support Us"
url = "https://ko-fi.com/clash"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Podcasts"
url = "podcasts"
weight = "2"
[[main]]
name = "News"
url = "blog"
weight = "3"
[[main]]
name = "Clans"
url = "clans"
weight = "4"
[[main]]
name = "FAQ"
url = "faq"
weight = "5"
[[main]]
name = "Support Us"
url = "https://ko-fi.com/clash"
weight = "6"
