[[footer_left]]
name = "About Us"
url = "#"
[[footer_left]]
name = "Quick Start"
url = "#"
[[footer_left]]
name = "Clans"
url = "pricing"
[[footer_middle]]
name = "Clash of Clans"
url = ""
[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Family Rules"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "News"
url = "blog"
weight = 2
[[main]]
name = "Clans"
url = "pricing"
weight = 3
[[main]]
name = "FAQ"
url = "faq"
weight = "4"
[[main]]
name = "Support Us"
url = "https://ko-fi.com/clash"
weight = "5"
