[[footer_left]]
name = "Married 2 Clash"
url = ""
[[footer_left]]
name = "Pineapples & Thorns"
url = ""
[[footer_middle]]
name = "Clash of Clans"
url = ""
[[footer_middle]]
name = "Clash Royale"
url = ""
[[footer_right]]
name = "Membership Terms"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "News"
url = "blog"
weight = 2
[[main]]
name = "Clans"
url = ""
weight = "3"
[[main]]
name = "FAQ"
url = "faq"
weight = "4"
[[main]]
name = "Support Us"
url = "https://ko-fi.com/clash"
weight = "5"
