author = "Clash Podcast"
contact_form_action = "#"
description = "The Clash Files"
image = "/images/tcfwordsblr200.png"
logo = "/images/tcfwordsblr200.png"
logo_width = "200px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[navigation_button]
enable = true
label = "Support Us"
link = "https://www.clashpodcast.com/blog/support-the-shows/"
[preloader]
enable = false
preloader = ""
[[social]]
title = "mastodon"
icon = "fab fa-mastodon"
link = "https://mastodon.social/@clashfiles"
rel = "me"
[[social]]
title = "youtube"
icon = "fab fa-youtube"
link = "https://www.youtube.com/channel/UCZSl_u5c1AMxeiRVpM8BdDg"
rel = "me"
[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/theclashfiles"
rel = "me"
[[social]]
title = "twitch"
icon = "fab fa-twitch"
link = "https://www.twitch.tv/clashfiles"
rel = "me"
[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/clashpod"
rel = "me"
